sudo: required
language: node_js
node_js:
- '10.1'
install:
- npm install
script:
- npm test # run tests

deploy:
 provider: script
 skip_cleanup: true
 script: sh $TRAVIS_BUILD_DIR/.travis/pu.sh
 on:
   branch: feature-fixes
   tags: false